name: local_turism
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  go_router: ^9.0.0
  http: ^0.13.6
  intl: ^0.18.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf        
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf        
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
