name: local_turism
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mocktail: ^1.0.3
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf        
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf        
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
